<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628010944 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
{
    // 1. Drop the FK so we can alter both columns freely
    $this->addSql('ALTER TABLE recording DROP CONSTRAINT IF EXISTS fk_recording_story');

    // 2. Fix recording.id
    $this->addSql('ALTER TABLE recording ALTER id TYPE UUID USING id::text::uuid');
    $this->addSql('ALTER TABLE recording ALTER id DROP IDENTITY IF EXISTS');

    // 3. Fix story.id (the missing piece)
    $this->addSql('ALTER TABLE story ALTER id TYPE UUID USING id::text::uuid');
    $this->addSql('ALTER TABLE story ALTER id DROP IDENTITY IF EXISTS');

    // 4. Fix the FK column on recording
    $this->addSql('ALTER TABLE recording ALTER story_id TYPE UUID USING story_id::text::uuid');

    // 5. Re-add the FK
    $this->addSql('ALTER TABLE recording ADD CONSTRAINT fk_recording_story FOREIGN KEY (story_id) REFERENCES story(id)');
}

public function down(Schema $schema): void
{
    $this->addSql('ALTER TABLE recording DROP CONSTRAINT IF EXISTS fk_recording_story');

    $this->addSql('ALTER TABLE recording ALTER story_id TYPE INT USING story_id::text::integer');
    $this->addSql('ALTER TABLE story ALTER id TYPE INT USING id::text::integer');
    $this->addSql('ALTER TABLE story ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    $this->addSql('ALTER TABLE recording ALTER id TYPE INT USING id::text::integer');
    $this->addSql('ALTER TABLE recording ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
}
}
